// Command docsite builds the documentation site from the .xtxt files in
// docs/pages.
//
// It uses the library rather than shelling out to the CLI, so the site is
// generated by the same code it documents: a page describing behaviour the
// parser does not have cannot be built, and a page that fails validation fails
// the build rather than shipping wrong.
//
// The shell — sidebar, per-page contents, prev/next — is this program's job.
// The content HTML is whatever RenderHTML produces, unmodified, so what a
// reader sees on the site and what `xtxt export html` writes cannot diverge.
package main

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"sort"
	"strings"

	xtxt "github.com/SaiMouli3/xtxt"
)

type page struct {
	Slug    string
	Title   string
	Summary string
	Body    string
	Outline []xtxt.Outline
}

func main() {
	src, out := "docs/pages", "_site/docs"
	if len(os.Args) > 2 {
		src, out = os.Args[1], os.Args[2]
	}
	if err := build(src, out); err != nil {
		fmt.Fprintln(os.Stderr, "docsite:", err)
		os.Exit(1)
	}
}

func build(src, out string) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	var names []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".xtxt") {
			names = append(names, e.Name())
		}
	}
	// Filenames carry the reading order, which is information the sidebar needs
	// and the content itself has no way to express.
	sort.Strings(names)
	if len(names) == 0 {
		return fmt.Errorf("no .xtxt pages in %s", src)
	}

	pages := make([]page, 0, len(names))
	for _, name := range names {
		p, err := load(filepath.Join(src, name))
		if err != nil {
			return err
		}
		pages = append(pages, p)
	}

	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	for i, p := range pages {
		var prev, next *page
		if i > 0 {
			prev = &pages[i-1]
		}
		if i < len(pages)-1 {
			next = &pages[i+1]
		}
		file := filepath.Join(out, p.Slug+".html")
		if err := os.WriteFile(file, []byte(shell(p, pages, prev, next)), 0o644); err != nil {
			return err
		}
	}
	fmt.Printf("docsite: %d pages -> %s\n", len(pages), out)
	return nil
}

func load(path string) (page, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return page{}, err
	}
	res := xtxt.ParseString(string(data))
	issues := append(append([]xtxt.Issue{}, res.Issues...), xtxt.Lint(res.Doc)...)
	for _, i := range issues {
		fmt.Fprintf(os.Stderr, "%s:%d: %s: %s\n", path, i.Line, i.Severity, i.Message)
	}
	// A page that does not parse is a page that would lie about the format.
	if res.HasErrors() {
		return page{}, fmt.Errorf("%s has errors", path)
	}

	meta := res.Doc.Metadata()
	title := meta["title"]
	if title == "" {
		for _, n := range res.Doc.Nodes {
			if n.Kind == xtxt.KindHeading {
				title = xtxt.InlineText(n.Text)
				break
			}
		}
	}

	base := strings.TrimSuffix(filepath.Base(path), ".xtxt")
	// Strip the ordering prefix: it belongs in the filename, not the URL.
	if i := strings.Index(base, "-"); i > 0 && isDigits(base[:i]) {
		base = base[i+1:]
	}

	return page{
		Slug:    base,
		Title:   title,
		Summary: meta["summary"],
		Body:    xtxt.RenderHTML(res.Doc, xtxt.HTMLOptions{}),
		Outline: xtxt.Extract(res.Doc).Outline,
	}, nil
}

func isDigits(s string) bool {
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return s != ""
}

// slug mirrors the renderer's heading anchors so the contents list links to
// the ids RenderHTML actually emitted.
func slug(text string, used map[string]int) string {
	var b strings.Builder
	for _, r := range strings.ToLower(xtxt.InlineText(text)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ', r == '-', r == '_':
			b.WriteByte('-')
		}
	}
	s := strings.Trim(b.String(), "-")
	for strings.Contains(s, "--") {
		s = strings.ReplaceAll(s, "--", "-")
	}
	if s == "" {
		s = "section"
	}
	used[s]++
	if n := used[s]; n > 1 {
		s = fmt.Sprintf("%s-%d", s, n-1)
	}
	return s
}

func shell(p page, all []page, prev, next *page) string {
	esc := html.EscapeString
	var b strings.Builder

	b.WriteString(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>` + esc(p.Title) + ` — XTXT</title>`)
	if p.Summary != "" {
		b.WriteString("\n<meta name=\"description\" content=\"" + esc(p.Summary) + "\">")
	}
	b.WriteString(`
<link rel="stylesheet" href="../xtxt.css">
<link rel="stylesheet" href="../docs.css">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><text y='26' font-size='26'>📄</text></svg>">
</head>
<body class="docs">
<a class="skip" href="#content">Skip to content</a>

<header class="docs-top">
  <a class="brand" href="../index.html">XTXT</a>
  <nav class="top-links">
    <a href="https://github.com/SaiMouli3/xtxt/blob/main/SPEC.md">Spec</a>
    <a href="../index.html#demo">Playground</a>
    <a href="https://github.com/SaiMouli3/xtxt">GitHub</a>
  </nav>
</header>

<div class="docs-layout">
  <nav class="sidebar" aria-label="Documentation">
    <ol>`)
	for _, q := range all {
		current := ""
		aria := ""
		if q.Slug == p.Slug {
			current = ` class="current"`
			aria = ` aria-current="page"`
		}
		b.WriteString("\n      <li" + current + "><a href=\"" + esc(q.Slug) + ".html\"" + aria + ">" + esc(q.Title) + "</a></li>")
	}
	b.WriteString(`
    </ol>
  </nav>

  <main id="content" class="xtxt docs-content">
` + p.Body + `
    <nav class="pager">`)
	if prev != nil {
		b.WriteString("\n      <a class=\"prev\" href=\"" + esc(prev.Slug) + ".html\"><span>Previous</span>" + esc(prev.Title) + "</a>")
	} else {
		b.WriteString("\n      <span></span>")
	}
	if next != nil {
		b.WriteString("\n      <a class=\"next\" href=\"" + esc(next.Slug) + ".html\"><span>Next</span>" + esc(next.Title) + "</a>")
	}
	b.WriteString(`
    </nav>
  </main>
`)

	// Only worth a contents rail when there is something to navigate.
	if len(p.Outline) > 2 {
		b.WriteString(`
  <nav class="toc" aria-label="On this page">
    <p class="toc-label">On this page</p>
    <ul>`)
		used := map[string]int{}
		for _, h := range p.Outline {
			id := slug(h.Text, used)
			if h.Level > 3 {
				continue
			}
			b.WriteString("\n      <li class=\"lvl-" + fmt.Sprint(h.Level) + "\"><a href=\"#" + esc(id) + "\">" + esc(h.Text) + "</a></li>")
		}
		b.WriteString(`
    </ul>
  </nav>`)
	}

	b.WriteString(`
</div>

<footer class="docs-foot">
  <p>Written in XTXT, rendered by <code>xtxt</code>. If the format cannot express it, this page cannot say it.</p>
</footer>`)

	// RenderHTML only inlines the runtime for a standalone document, and this
	// tool builds the page shell itself. Ship it where a chart exists, and
	// nowhere else, so a page with no chart stays script-free.
	if strings.Contains(p.Body, "data-xtxt-chart") {
		b.WriteString("\n<script>" + xtxt.ChartRuntime + "</script>")
	}

	b.WriteString(`
</body>
</html>
`)
	return b.String()
}
